import { useI18n } from '../../lib/i18n'
import {useEffect,useState} from 'react';
import type {Project} from '../../../shared/project';
import type {MotionScene} from '../../../shared/motion';
import {Modal,Select,Tooltip} from '../../components/ui';
import {Icon} from '../../components/Icon';
import {api} from '../../lib/api';
const preferredModels=[{value:'anthropic/claude-opus-5.5',label:'Claude Opus 5.5'},{value:'openai/gpt-6-astra',label:'GPT-6 Astra'},{value:'openai/gpt-6-astra-pro',label:'GPT-6 Astra Pro'}];
type Job={id:string;status:string;error?:string};
export function MotionAssistant({open,onClose,project,onScene,onConnect}:{open:boolean;onClose:()=>void;project:Project;onScene:(scene:MotionScene)=>void;onConnect:()=>void}){
  const { t } = useI18n()
 const[models,setModels]=useState(preferredModels);
 const[prompt,setPrompt]=useState('');const[model,setModel]=useState(preferredModels[0].value);const[job,setJob]=useState<Job|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{if(!open)return;let active=true;void api<{models:{id:string;name:string}[]}>('/models?provider=openrouter&kind=motion').then(catalog=>{if(!active)return;const available=preferredModels.filter(item=>catalog.models.some(model=>model.id===item.value));if(available.length){setModels(available);setModel(current=>available.some(item=>item.value===current)?current:available[0].value);}}).catch(()=>{});return()=>{active=false;};},[open]);
 useEffect(()=>{if(!job||!['queued','running'].includes(job.status))return;const timer=setTimeout(async()=>{try{const next=await api<Job>(`/jobs/${job.id}`);setJob(next);if(next.status==='complete'){const updated=await api<Project>(`/projects/${project.id}`);onScene(updated.motion);}if(next.status==='error')setError(next.error||t('A geração não foi concluída.'));}catch(e){setError(e instanceof Error?e.message:t('Runtime indisponível.'));}},1800);return()=>clearTimeout(timer);},[job,project.id,onScene]);
 const generate=async()=>{setBusy(true);setError('');try{setJob(await api<Job>('/generate',{method:'POST',body:JSON.stringify({provider:'openrouter',kind:'motion',model,prompt,projectId:project.id})}));}catch(e){setError(e instanceof Error?e.message:t('Não foi possível iniciar.'));}finally{setBusy(false);}};
 const pending=busy||!!job&&['queued','running'].includes(job.status);
 return <Modal open={open} onOpenChange={o=>!o&&onClose()} title={t("Gerar motion")}><div className="form-stack"><label>Prompt<Tooltip content={t("Prompt")}><textarea className="text-input" rows={5} placeholder={t("Uma abertura de 6 segundos para a Onun. Tipografia grande, formas em rosa, entradas suaves e uma transição final elegante…")} value={prompt} onChange={e=>setPrompt(e.target.value)}/></Tooltip></label><label>{t("Modelo OpenRouter")}<fieldset className="motion-model-select" disabled={pending}><Select label={t("Modelo OpenRouter")} value={model} options={models} onChange={setModel}/></fieldset></label><div className="credential-note"><Icon name="motion" size={17}/><p>{t("Substitui a cena atual. Você pode desfazer.")}</p></div>{error&&<p className="inline-error" role="alert">{error}</p>}{job?.status==='complete'&&<p className="settings-message">{t("Cena criada. Ela já está aberta no editor.")}</p>}<Tooltip content={pending?t('Compondo sua cena…'):t('Criar cena com IA')}><button className="button primary" onClick={generate} disabled={pending||!prompt.trim()||!model.trim()}><Icon name={pending?'clock':'motion'} size={16}/>{pending?t('Compondo sua cena…'):t('Criar cena com IA')}</button></Tooltip>{pending&&job&&<Tooltip content={t("Cancelar geração")}><button className="button" onClick={async()=>setJob(await api(`/jobs/${job.id}`,{method:'DELETE'}))}>{t("Cancelar geração")}</button></Tooltip>}<Tooltip content={t("Usar Claude ou Codex via MCP")}><button className="button" onClick={onConnect}><Icon name="terminal" size={16}/>{t("Usar Claude ou Codex via MCP")}</button></Tooltip><small className="muted">{t("A geração da cena usa os créditos da sua chave OpenRouter.")}</small></div></Modal>;
}
