import {t} from '../../lib/i18n';
import {useEffect,useState} from 'react';
import {Modal} from '../../components/ui';
import {Icon} from '../../components/Icon';
import {api} from '../../lib/api';
type Provider='openrouter'|'higgsfield';
type SettingsState={providers:Record<Provider,{configured:boolean;source:string}>};
export function Settings({open,onClose,initialTab='providers',initialProvider='openrouter'}:{open:boolean;onClose:()=>void;initialTab?:'providers'|'mcp';initialProvider?:Provider}){
 const[exactConfig,setExactConfig]=useState<unknown>(null);
 const[tab,setTab]=useState(initialTab);const[provider,setProvider]=useState<Provider>('openrouter');const[key,setKey]=useState('');const[state,setState]=useState<SettingsState|null>(null);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[copied,setCopied]=useState(false);
 useEffect(()=>{if(!open){setKey('');return;}setTab(initialTab);setProvider(initialProvider);setMessage('');api('/mcp/config').then(setExactConfig).catch(()=>{});api<SettingsState>('/settings').then(setState).catch(()=>setMessage(t("Runtime local indisponível. Inicie com npm run dev.")));},[open,initialTab,initialProvider]);
 const save=async(clear=false)=>{setBusy(true);setMessage('');try{const next=await api<SettingsState>('/settings',{method:'POST',body:JSON.stringify({provider,apiKey:key,clear})});setState(next);setKey('');setMessage(clear?t("Chave salva removida deste dispositivo."):t("Chave salva. Ela continuará ativa ao reabrir o OnunSpace."));}catch(error){setMessage(error instanceof Error?error.message:t("Não foi possível salvar."));}finally{setBusy(false);}};
 const config=JSON.stringify(exactConfig??{mcpServers:{'onun-space':{command:'node',args:['--import','tsx','server/mcp.ts'],cwd:'/caminho/para/OnunSpace'}}},null,2);
 return <Modal open={open} onOpenChange={o=>!o&&onClose()} title={t("Configurações")}><div className="settings-tabs"><button className={tab==='providers'?'active':''} onClick={()=>setTab('providers')}><Icon name="link" size={16}/>{t("Provedores de IA")}</button><button className={tab==='mcp'?'active':''} onClick={()=>setTab('mcp')}><Icon name="mcp" size={16}/>{t("Conexão MCP")}</button></div>{tab==='providers'?<div className="form-stack"><div className="provider-options">{(['openrouter','higgsfield'] as const).map(p=><button className={provider===p?'selected':''} key={p} onClick={()=>{setProvider(p);setKey('');setMessage('');}}><img src={p==='openrouter'?'/assets/openrouter.svg':'/assets/providers/higgsfield.svg'} alt=""/><strong>{p==='openrouter'?'OpenRouter':'Higgsfield'}</strong><small>{state?.providers[p]?.configured?t("Configurado"):t("Não conectado")}</small></button>)}</div><label>{t("Chave da API")}<input className="text-input" type="password" autoComplete="off" placeholder={provider==='openrouter'?'sk-or-v1-…':t("Cole sua API key completa")} aria-describedby={provider==='higgsfield'?'higgsfield-key-help':undefined} value={key} onChange={e=>setKey(e.target.value)}/></label>{provider==='higgsfield'&&<p className="credential-help" id="higgsfield-key-help">{t("Cole a API key completa copiada do painel Higgsfield.")}</p>}<div className="credential-note"><Icon name="lock" size={16}/><p>{t("A chave fica salva neste dispositivo e permanece ativa após reiniciar.")}</p></div><div className="settings-actions"><a href={provider==='openrouter'?'https://openrouter.ai/settings/keys':'https://console.higgsfield.ai/'} target="_blank" rel="noopener noreferrer">{t("Obter uma chave")}<Icon name="arrow" size={13}/></a>{state?.providers[provider]?.configured&&<button className="button" onClick={()=>save(true)} disabled={busy}>{t("Desconectar")}</button>}<button className="button primary" onClick={()=>save()} disabled={busy||!key.trim()}>{busy?t("Salvando…"):t("Conectar provedor")}</button></div></div>:<div className="mcp-content"><span className="section-label">{t("CONFIGURAÇÃO STDIO")}</span><pre tabIndex={0} aria-label={t("Configuração MCP")}>{config}</pre><button className="button" onClick={async()=>{await navigator.clipboard.writeText(config);setCopied(true);}}><Icon name={copied?'check':'copy'} size={15}/>{copied?t("Copiado"):t("Copiar configuração")}</button><p className="mcp-help">{t("Mantenha o runtime local aberto. A configuração inclui os caminhos deste computador. Instruções completas em")}<code>docs/local-runtime.md</code>.</p></div>}{message&&<p className="settings-message" role="status">{message}</p>}</Modal>;
}
