import {t} from '../lib/i18n';
import {Tooltip} from './Tooltip';
export {Tooltip} from './Tooltip';
import {useContext,type ReactNode} from 'react';
import {GuidedTourMode} from './guided-tour-context';
import * as Dialog from '@radix-ui/react-dialog';
import * as Dropdown from '@radix-ui/react-dropdown-menu';
import {Icon,type IconName} from './Icon';
export function IconButton({icon,label,onClick,active=false,disabled=false,className=''}:{icon:IconName;label:string;onClick?:()=>void;active?:boolean;disabled?:boolean;className?:string}){return <Tooltip content={label}><button type="button" aria-label={label} className={`icon-button ${active?'active':''} ${className}`} onClick={onClick} disabled={disabled}><Icon name={icon}/></button></Tooltip>;}
export function Modal({open,onOpenChange,title,description,children,wide=false}:{open:boolean;onOpenChange:(open:boolean)=>void;title:string;description?:string;children:ReactNode;wide?:boolean}){const guided=useContext(GuidedTourMode);return <Dialog.Root modal={!guided} open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={`modal ${wide?'wide':''}`} aria-describedby={description?'modal-description':undefined} onOpenAutoFocus={event=>{if(guided)event.preventDefault();}} onInteractOutside={event=>{if(guided)event.preventDefault();}} onEscapeKeyDown={event=>{if(guided)event.preventDefault();}}><div className="modal-heading"><Dialog.Title>{title}</Dialog.Title><Dialog.Close asChild><button className="icon-button" aria-label={t("Fechar")}><Icon name="close"/></button></Dialog.Close></div>{description&&<Dialog.Description id="modal-description" className="modal-description">{description}</Dialog.Description>}{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export interface MenuItem{label:string;value:string;icon?:IconName;danger?:boolean;disabled?:boolean;hint?:string;children?:MenuItem[];separator?:boolean;className?:string;selected?:boolean}
function MenuItems({items,onSelect}:{items:MenuItem[];onSelect:(value:string)=>void}){
 if(items.length&&items.every(item=>item.selected!==undefined))return <Dropdown.RadioGroup value={items.find(item=>item.selected)?.value} onValueChange={onSelect}>{items.map(item=><Dropdown.RadioItem key={item.value} value={item.value} disabled={item.disabled} className={`menu-item menu-choice ${item.className??''}`}>
  {item.icon&&<Icon name={item.icon} size={16}/>}<span>{item.label}</span><Dropdown.ItemIndicator className="menu-choice-check"><Icon name="check" size={14}/></Dropdown.ItemIndicator>
 </Dropdown.RadioItem>)}</Dropdown.RadioGroup>;
 return <>{items.map((item,i)=><span className="menu-wrapper" key={`${item.value}-${i}`}>{item.separator&&<Dropdown.Separator className="menu-separator"/>}{item.children?<Dropdown.Sub><Dropdown.SubTrigger className={`menu-item ${item.className??''}`}>{item.icon&&<Icon name={item.icon} size={17}/>}<span>{item.label}</span><Icon name="chevron-right" size={14}/></Dropdown.SubTrigger><Dropdown.Portal><Dropdown.SubContent className="dropdown submenu" sideOffset={8} alignOffset={-5}><MenuItems items={item.children} onSelect={onSelect}/></Dropdown.SubContent></Dropdown.Portal></Dropdown.Sub>:<Dropdown.Item className={`menu-item ${item.danger?'danger':''} ${item.className??''}`} disabled={item.disabled} onSelect={()=>onSelect(item.value)}>{item.icon&&<Icon name={item.icon} size={17}/>}<span>{item.label}</span>{item.hint&&<kbd>{item.hint}</kbd>}</Dropdown.Item>}</span>)}</>;}
export function Menu({trigger,label,items,onSelect,align='start',className='',open,onOpenChange}:{trigger:ReactNode;label:string;items:MenuItem[];onSelect:(value:string)=>void;align?:'start'|'end';className?:string;open?:boolean;onOpenChange?:(open:boolean)=>void}){const guided=useContext(GuidedTourMode);return <Dropdown.Root modal={!guided} open={open} onOpenChange={onOpenChange}><Tooltip content={label}><Dropdown.Trigger asChild><button aria-label={label} className={className||'chip'}>{trigger}</button></Dropdown.Trigger></Tooltip><Dropdown.Portal><Dropdown.Content className="dropdown" align={align} sideOffset={8} onCloseAutoFocus={event=>{if(guided)event.preventDefault();}} onInteractOutside={event=>{if(guided)event.preventDefault();}} onEscapeKeyDown={event=>{if(guided)event.preventDefault();}}><MenuItems items={items} onSelect={onSelect}/></Dropdown.Content></Dropdown.Portal></Dropdown.Root>;}
export function Select({value,options,onChange,label}:{value:string;options:{value:string;label:string}[];onChange:(value:string)=>void;label:string}){return <Menu label={label} className="select-control" trigger={<><span>{options.find(o=>o.value===value)?.label??value}</span><Icon name="chevron-down" size={14}/></>} items={options.map(o=>({...o,icon:o.value===value?'check':undefined}))} onSelect={onChange}/>;}
