import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {once} from 'node:events';
import type {AddressInfo} from 'node:net';
import {chromium} from 'playwright';
import {unzipSync} from 'fflate';
import {createApp} from '../server/app.js';
import {defaultScene} from '../shared/motion.js';

const temporary=await mkdtemp(join(tmpdir(),'onun-backup-ui-'));
const runtime=createApp({dataDirectory:join(temporary,'runtime')});
runtime.server.listen(0,'127.0.0.1');await once(runtime.server,'listening');
const base=`http://127.0.0.1:${(runtime.server.address() as AddressInfo).port}`;
const projectId='qa-backup-isolated';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZasAAAAASUVORK5CYII=';
const original=await runtime.projects.save({id:projectId,name:'[QA] Backup',edges:[],motion:defaultScene,nodes:[{id:'image',kind:'image',title:'Backup image',x:120,y:100,width:300,prompt:'',model:'',provider:'openrouter',aspectRatio:'1:1',resolution:'1K',count:1,status:'none',media:`data:image/png;base64,${png}`}]});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900},colorScheme:'dark'});
const checks:string[]=[];const errors:string[]=[];const output=resolve('.figma-app/artifacts/actual');
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/api/**',async route=>{const url=new URL(route.request().url());const response=await route.fetch({url:base+url.pathname+url.search});await route.fulfill({response});});
try{
 await page.goto(`http://127.0.0.1:5178/?project=${projectId}&qa=1`);
 await page.getByRole('button',{name:'Workspace menu',exact:true}).click();
 await page.getByRole('menuitem',{name:'Project backup',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Project backup',exact:true});
 const path=dialog.getByRole('textbox',{name:'Backup folder',exact:true});
 await path.waitFor();await path.fill(join(temporary,'chosen'));
 await dialog.getByRole('button',{name:'Save folder',exact:true}).click();
 await dialog.getByText('Folder remembered for this project',{exact:true}).waitFor();
 await dialog.getByRole('button',{name:'Create ZIP backup',exact:true}).click();
 await dialog.getByText('Backup saved',{exact:true}).waitFor();
 const info=await runtime.backups.settings(projectId);assert.ok(info.lastBackup);
 const zip=await readFile(info.lastBackup.path);const archive=unzipSync(zip);
 assert.equal(JSON.parse(Buffer.from(archive['project.json']).toString()).name,original.name);
 assert.ok(Object.keys(archive).some(name=>name.endsWith('.png')));
 checks.push('UI created a real ZIP in the selected folder, with project and image bytes.');
 const href=await dialog.getByRole('link',{name:'Download ZIP',exact:true}).getAttribute('href');assert.equal(href,info.lastBackup.downloadUrl);
 assert.deepEqual(Buffer.from(await(await fetch(base+href)).arrayBuffer()),zip);
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Workspace menu',exact:true}).click();await page.getByRole('menuitem',{name:'Project backup',exact:true}).click();
 await page.waitForFunction(destination=>(document.querySelector('.backup-destination input') as HTMLInputElement)?.value===destination,info.destination);
 checks.push('Reopened dialog retained the destination and downloadable archive.');
 await dialog.getByLabel('Select ZIP backup',{exact:true}).setInputFiles({name:'backup.onun.zip',mimeType:'application/zip',buffer:zip});
 await dialog.getByText('Backup restored',{exact:true}).waitFor();
 const projects=await runtime.projects.list();assert.equal(projects.length,2);
 const restored=await runtime.projects.get(projects.find(project=>project.id!==projectId)!.id);
 assert.notEqual(restored.id,original.id);assert.ok(restored.nodes[0].media?.startsWith(`/api/projects/${restored.id}/assets/`));
 assert.deepEqual(await runtime.projects.get(projectId),original);
 checks.push('ZIP upload restored a new project and preserved the source revision/content.');
 await mkdir(output,{recursive:true});await page.screenshot({path:join(output,'backup-smoke.png')});
 await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.deepEqual(errors,[]);
 checks.push('Escape closed the accessible dialog without page errors.');
 await writeFile(join(output,'backup-smoke.json'),JSON.stringify({timestamp:new Date().toISOString(),checks,errors,isolation:'All API requests routed to ephemeral runtime in a temporary directory. No user project read or written.',archiveBytes:zip.length},null,2));
 console.log(JSON.stringify({checks,archiveBytes:zip.length}));
}finally{await browser.close();await new Promise<void>(resolve=>runtime.server.close(()=>resolve()));await rm(temporary,{recursive:true,force:true});}
